# on every push or pull request

# name: CI Pipeline

# on:
#   push:
#     branches: ["dev","main"]
#   pull_request:
#     branches: ["main"]

# jobs:
#   build-test-docker:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.11"

#       - name: Install dependencies
#         run: |
#           pip install -r requirements.txt

#       - name: Run tests
#         run: |
#           pytest -v

#       - name: Build Docker image
#         run: |
#           docker build -t flask-devops-app .


name: DevSecOps CI Pipeline
 
on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["main"]
 
jobs:
  build-test-docker:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Start Infrastructure (DB + App)
        run: |
          # Use 'docker compose' (V2) to avoid 'command not found'
          docker compose up -d --build
          # Essential for PostgreSQL initialization
          sleep 15
 
      - name: Run Automated Security Tests
        # Executes pytest inside the container to verify Data Isolation
        run: |
          docker compose exec -T web pytest -v
 
      - name: Container Status on Failure
        if: failure()
        run: docker compose logs