# on every push or pull request

# name: CI Pipeline

# on:
#   push:
#     branches: ["dev","main"]
#   pull_request:
#     branches: ["main"]

# jobs:
#   build-test-docker:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.11"

#       - name: Install dependencies
#         run: |
#           pip install -r requirements.txt

#       - name: Run tests
#         run: |
#           pytest -v

#       - name: Build Docker image
#         run: |
#           docker build -t flask-devops-app .


name: DevSecOps CI Pipeline

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Infrastructure (PostgreSQL + Flask)
        run: |
          docker compose up -d --build
          sleep 30 # Increased wait time for DB stability

      - name: Seed Database & Verify Hashing
        run: |
          # This creates the hashed users for your evidence
          docker compose exec -T web python seed.py 
          # This prints the hashes into the GitHub logs so you can screenshot them!
          docker exec app-db psql -U postgres -d appdb -c "SELECT username, password_hash FROM users;"

      - name: Run Security & Data Isolation Tests
        run: |
          # These are your automated Security Gates
          docker compose exec -T web pytest -v

      - name: Verify Infrastructure Status
        run: docker ps